<a href="https://colab.research.google.com/github/jarvis-2003/deeplearning/blob/main/fundamentals_of_deeplearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00 . PyTorch Fundamentals

Resourse notebook : https://www.learnpytorch.io/00_pytorch_fundamentals/

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


## INTRODUCTION TO TENSOR

### Creating tensors

Pytorch tensors are created using torch.tensor() = https://pytorch.org/docs/stable/tensors.html


In [4]:
# scalar
scaler = torch.tensor(7)
scaler

tensor(7)

In [5]:
scaler.ndim


0

In [6]:
# allows to get the tensor back as python int
scaler.item()

7

In [7]:
# VECTOR
vector = torch.tensor([7,7])
vector


tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim
MATRIX.shape

torch.Size([2, 2])

In [12]:
#  TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
# practice on tensor
TENSORP = torch.tensor([[[1,2,3],[3,4,5],[5,6,7]],[[10,20,30],[30,40,50],[50,60,70]]])
TENSORP

tensor([[[ 1,  2,  3],
         [ 3,  4,  5],
         [ 5,  6,  7]],

        [[10, 20, 30],
         [30, 40, 50],
         [50, 60, 70]]])

In [14]:
TENSORP.ndim

3

In [15]:
TENSORP.shape

torch.Size([2, 3, 3])

### RANDOM TENSORS
Why Random Tensors?

Random tensors are important because the way many neural networks learns is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

Start with random numbers --> look at the data --> update random numbers --> look at data  --> update random number


In [16]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4171, 0.9248, 0.9832, 0.4180],
        [0.4150, 0.9773, 0.0394, 0.4303],
        [0.3304, 0.3933, 0.9566, 0.0623]])

In [17]:
# creating a tensor of image size
random_image_size_tensor = torch.rand(3,224,224)
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [18]:
random_image_size_tensor

tensor([[[0.5422, 0.6998, 0.7468,  ..., 0.0449, 0.5495, 0.9361],
         [0.4628, 0.1147, 0.5861,  ..., 0.3098, 0.4117, 0.8645],
         [0.5795, 0.8819, 0.5504,  ..., 0.2251, 0.5478, 0.4044],
         ...,
         [0.6572, 0.5554, 0.1519,  ..., 0.8121, 0.7636, 0.0676],
         [0.2392, 0.5003, 0.3808,  ..., 0.2284, 0.0904, 0.1965],
         [0.2726, 0.0415, 0.8218,  ..., 0.1052, 0.6064, 0.5626]],

        [[0.2939, 0.1904, 0.2493,  ..., 0.0697, 0.0420, 0.5488],
         [0.7198, 0.7890, 0.8736,  ..., 0.1480, 0.1650, 0.3880],
         [0.9299, 0.2555, 0.6229,  ..., 0.6371, 0.9880, 0.5641],
         ...,
         [0.3453, 0.8683, 0.5131,  ..., 0.7054, 0.8663, 0.9023],
         [0.3646, 0.5002, 0.8528,  ..., 0.0488, 0.2518, 0.9826],
         [0.3613, 0.8014, 0.1727,  ..., 0.2895, 0.0104, 0.4719]],

        [[0.5395, 0.8910, 0.5773,  ..., 0.5085, 0.0400, 0.2626],
         [0.1319, 0.2659, 0.9817,  ..., 0.2331, 0.8568, 0.8430],
         [0.1359, 0.5143, 0.6246,  ..., 0.5601, 0.4761, 0.

## ZEROS AND ONES TENSOR

In [19]:
# create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zeros * random_tensor
# can you used for masking other values like making all the tensor to 0

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# creating tensors with all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Creating Range Tensors and tensors - like

In [22]:
# use torch.arange
one_to_ten = torch.arange(0,101,10)
one_to_ten


tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [23]:
# creating tensors like
tlike = torch.zeros_like(one_to_ten)
tlike

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor DataTypes
**NOTE:** Tensor datatype is one of the 3 big errors youwill run into in pytorch and deeplearning

1.Tensors not right datatpe i.e doing operation on two different data type like matrix multiplication will cause trouble

2.Tensors not right shape matrix multiplication needs a shape criteria to perform the
multiplication between two tensors

3.tensors not on the right device


> Add blockquote



In [24]:
# creating a float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype
# The Default value for the torch is float 32 even we spicify NONE

torch.float32

In [26]:
# lets try giving dtypes
variable_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype= torch.float16,
                               device=None,
                               requires_grad= False) #whether or not to track gradients with this tensors operation

variable_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
(float_32_tensor * variable_tensor).dtype

torch.float32

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (Element-wise)
* ZeroDivisionError
* MatrixMultiplication

In [28]:
# Addition
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [30]:
#multiplication
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [32]:
# Subtraction
tensor - 10

tensor([ 0, 10, 20])

### Matrix multiplication

Two main way of performing multiplication in neural networks and deep learning

1.Elementwise Multiplication

2.Matrix multiplication(dot product)

There are two main rules that a matrix multiplication needs to be satisfy:

1.The **Inner dimension** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2.The resulting matrix has the shape of **outer dimension**
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`



In [35]:
# element wise multiplication
tensor * tensor

tensor([100, 400, 900])

In [37]:
# matrix multiplication
torch.matmul(tensor,tensor)

tensor(1400)

You get error when we try to multiply same shape matrices
* `(3,2) @ (3,2)` --> 'ERROR'

What we can do is : Tranpose on of the matrix to get the inner dimension same
*`(3,2) @ (2,3)` --> `(3,3)`

In [40]:
tensor_A = torch.tensor([[1,2],
                         [4,5],
                         [7,8]])

tensor_B = torch.tensor([[11,12],
                        [14,15],
                        [17,18]])

In [42]:
# to fix the dimension issue problem we do
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 35,  44,  53],
        [104, 131, 158],
        [173, 218, 263]])

In [43]:
tensor_B.T
# the rows became column and column became rows

tensor([[11, 14, 17],
        [12, 15, 18]])

### Finding the mean ,max,sum,etc (tensor aggregation)

In [46]:
# lets take a range tensor
x = torch.arange(0,101,10,dtype=torch.float32)
x

tensor([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [48]:
# find min
x.min() , torch.min(x)

(tensor(0.), tensor(0.))

In [50]:
# find max
x.max(),torch.max(x)

(tensor(100.), tensor(100.))

In [53]:
# find mean - note : the torch.mean() function works oly with float or complex value tensors
torch.mean(x),x.mean()

(tensor(50.), tensor(50.))

In [54]:
# find sum
torch.sum(x),x.sum()

(tensor(550.), tensor(550.))

In [58]:
# find the position in tensor that has minimum value with argmin() -> returns the index po
x.argmin()


tensor(0)

In [59]:
# find argmax
x.argmax()

tensor(10)

In [60]:
x[10]

tensor(100.)