<a href="https://colab.research.google.com/github/jarvis-2003/deeplearning/blob/main/fundamentals_of_deeplearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00 . PyTorch Fundamentals

Resourse notebook : https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


## INTRODUCTION TO TENSOR

### Creating tensors

Pytorch tensors are created using torch.tensor() = https://pytorch.org/docs/stable/tensors.html


In [2]:
# scalar
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim


0

In [4]:
# allows to get the tensor back as python int
scaler.item()

7

In [5]:
# VECTOR
vector = torch.tensor([7,7])
vector


tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim
MATRIX.shape

torch.Size([2, 2])

In [10]:
#  TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
# practice on tensor
TENSORP = torch.tensor([[[1,2,3],[3,4,5],[5,6,7]],[[10,20,30],[30,40,50],[50,60,70]]])
TENSORP

tensor([[[ 1,  2,  3],
         [ 3,  4,  5],
         [ 5,  6,  7]],

        [[10, 20, 30],
         [30, 40, 50],
         [50, 60, 70]]])

In [12]:
TENSORP.ndim

3

In [13]:
TENSORP.shape

torch.Size([2, 3, 3])

### RANDOM TENSORS
Why Random Tensors?

Random tensors are important because the way many neural networks learns is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

Start with random numbers --> look at the data --> update random numbers --> look at data  --> update random number


In [14]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6348, 0.3047, 0.2138, 0.5741],
        [0.4737, 0.8413, 0.9398, 0.6585],
        [0.1589, 0.3471, 0.0138, 0.3244]])

In [15]:
# creating a tensor of image size
random_image_size_tensor = torch.rand(3,224,224)
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [16]:
random_image_size_tensor

tensor([[[0.8607, 0.2417, 0.1069,  ..., 0.3778, 0.7360, 0.5903],
         [0.7761, 0.8365, 0.4827,  ..., 0.5020, 0.4540, 0.7516],
         [0.5466, 0.2078, 0.0900,  ..., 0.5451, 0.1398, 0.6807],
         ...,
         [0.5787, 0.5638, 0.6807,  ..., 0.9821, 0.0102, 0.2701],
         [0.2584, 0.4316, 0.9574,  ..., 0.3773, 0.3760, 0.1156],
         [0.5048, 0.9787, 0.7021,  ..., 0.3575, 0.2380, 0.5079]],

        [[0.1550, 0.4686, 0.9498,  ..., 0.3925, 0.8245, 0.1373],
         [0.6409, 0.2956, 0.3470,  ..., 0.0170, 0.2501, 0.8720],
         [0.1451, 0.5803, 0.8987,  ..., 0.7196, 0.3774, 0.5190],
         ...,
         [0.6782, 0.6059, 0.2708,  ..., 0.5923, 0.6429, 0.8465],
         [0.8972, 0.8923, 0.7736,  ..., 0.5496, 0.2358, 0.6990],
         [0.9103, 0.4822, 0.9480,  ..., 0.6236, 0.5546, 0.8632]],

        [[0.7396, 0.1784, 0.2334,  ..., 0.2970, 0.7029, 0.2858],
         [0.7696, 0.3838, 0.8669,  ..., 0.3923, 0.5259, 0.2788],
         [0.9124, 0.0048, 0.2345,  ..., 0.4122, 0.9308, 0.

## ZEROS AND ONES TENSOR

In [17]:
# create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
zeros * random_tensor
# can you used for masking other values like making all the tensor to 0

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
# creating tensors with all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Creating Range Tensors and tensors - like

In [20]:
# use torch.arange
one_to_ten = torch.arange(0,101,10)
one_to_ten


tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [21]:
# creating tensors like
tlike = torch.zeros_like(one_to_ten)
tlike

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor DataTypes
**NOTE:** Tensor datatype is one of the 3 big errors youwill run into in pytorch and deeplearning

1.Tensors not right datatpe i.e doing operation on two different data type like matrix multiplication will cause trouble

2.Tensors not right shape matrix multiplication needs a shape criteria to perform the
multiplication between two tensors

3.tensors not on the right device


> Add blockquote



In [22]:
# creating a float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [23]:
float_32_tensor.dtype
# The Default value for the torch is float 32 even we spicify NONE

torch.float32

In [24]:
# lets try giving dtypes
variable_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype= torch.float16,
                               device=None,
                               requires_grad= False) #whether or not to track gradients with this tensors operation

variable_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
(float_32_tensor * variable_tensor).dtype

torch.float32

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (Element-wise)
* ZeroDivisionError
* MatrixMultiplication

In [26]:
# Addition
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [27]:
#multiplication
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [28]:
# Subtraction
tensor - 10

tensor([ 0, 10, 20])

### Matrix multiplication

Two main way of performing multiplication in neural networks and deep learning

1.Elementwise Multiplication

2.Matrix multiplication(dot product)

There are two main rules that a matrix multiplication needs to be satisfy:

1.The **Inner dimension** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2.The resulting matrix has the shape of **outer dimension**
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`



In [29]:
# element wise multiplication
tensor * tensor

tensor([100, 400, 900])

In [30]:
# matrix multiplication
torch.matmul(tensor,tensor)

tensor(1400)

You get error when we try to multiply same shape matrices
* `(3,2) @ (3,2)` --> 'ERROR'

What we can do is : Tranpose on of the matrix to get the inner dimension same
*`(3,2) @ (2,3)` --> `(3,3)`

In [31]:
tensor_A = torch.tensor([[1,2],
                         [4,5],
                         [7,8]])

tensor_B = torch.tensor([[11,12],
                        [14,15],
                        [17,18]])

In [32]:
# to fix the dimension issue problem we do
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 35,  44,  53],
        [104, 131, 158],
        [173, 218, 263]])

In [33]:
tensor_B.T
# the rows became column and column became rows

tensor([[11, 14, 17],
        [12, 15, 18]])

### Finding the mean ,max,sum,etc (tensor aggregation)

In [34]:
# lets take a range tensor
x = torch.arange(0,101,10,dtype=torch.float32)
x

tensor([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [35]:
# find min
x.min() , torch.min(x)

(tensor(0.), tensor(0.))

In [36]:
# find max
x.max(),torch.max(x)

(tensor(100.), tensor(100.))

In [37]:
# find mean - note : the torch.mean() function works oly with float or complex value tensors
torch.mean(x),x.mean()

(tensor(50.), tensor(50.))

In [38]:
# find sum
torch.sum(x),x.sum()

(tensor(550.), tensor(550.))

In [39]:
# find the position in tensor that has minimum value with argmin() -> returns the index po
x.argmin()


tensor(0)

In [40]:
# find argmax
x.argmax()

tensor(10)

In [41]:
x[10]

tensor(100.)

## Reshaping , stacking , squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape

* View - return a view of an input tensor of certain shape but keep the same memory as its original tensor

* Stacking- combine multiple tensor on top of each other (vstack) or side by side(hstack)

* squeeze - removes all `1` dimensions from a tensor

* Unsqueeze - add `1` dimension to a
target tensor

* permute- return a view of the input with dimensions permuted(swapped) in a certain way

In [42]:
# lets create a tensor
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [43]:
# add an extra dimension
x_reshaped = torch.reshape(x,shape=(9,1))
x_reshaped , x_reshaped.shape
# to reshape the original tensor length must be equal to the multiplication of the reshaping param
# for example : if original tensor is (2,3) the we can reshape it to (1,6)  or (6,1) or (2,3) or any multiple of 6

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [44]:
# Change the view
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [45]:
# changing something in view z will affect or change the things in x also
z[0][0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [46]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [47]:
# torch.sqeeze() - remove all the 1 dimension will be removed
x = torch.zeros(3,1,2,4)
x.size()
# [[[
#    [[0,0]],
#    [[0,0]]
# ]],[[[[0,0]],[[0,0]]]]]
y = torch.squeeze(x,0)
y.size()

torch.Size([3, 1, 2, 4])

In [48]:
z = torch.unsqueeze(x,3)
z.size()

torch.Size([3, 1, 2, 1, 4])

In [49]:
## torch.permute - rearranges the dimension of a target tensor in a specified order
x_original =torch.rand(224,224,3)
# permute the original tensor
x_permuted = x_original.permute(2,0,1) # shifts the indexs 2-0,0->1,1->2
x_permuted.shape
x_permuted


tensor([[[0.6469, 0.8207, 0.9877,  ..., 0.3460, 0.4781, 0.5874],
         [0.0782, 0.2782, 0.7920,  ..., 0.7389, 0.0593, 0.5554],
         [0.7907, 0.0144, 0.8375,  ..., 0.2040, 0.1568, 0.2588],
         ...,
         [0.1680, 0.7859, 0.2360,  ..., 0.6452, 0.9960, 0.2164],
         [0.5376, 0.4511, 0.1790,  ..., 0.4995, 0.0670, 0.6124],
         [0.5028, 0.1951, 0.0439,  ..., 0.1560, 0.4567, 0.8005]],

        [[0.4514, 0.8783, 0.0495,  ..., 0.8785, 0.0779, 0.8305],
         [0.9743, 0.7833, 0.5693,  ..., 0.2547, 0.6456, 0.1162],
         [0.6547, 0.0275, 0.8932,  ..., 0.3375, 0.9419, 0.3542],
         ...,
         [0.6762, 0.1156, 0.7529,  ..., 0.1390, 0.5004, 0.2084],
         [0.7918, 0.2533, 0.1399,  ..., 0.6101, 0.9073, 0.8690],
         [0.9258, 0.4339, 0.8913,  ..., 0.5842, 0.7445, 0.0475]],

        [[0.1166, 0.0770, 0.7559,  ..., 0.8934, 0.7961, 0.6689],
         [0.3459, 0.9741, 0.7363,  ..., 0.4429, 0.6846, 0.2414],
         [0.6425, 0.1285, 0.9485,  ..., 0.4387, 0.9292, 0.

# Indexing (select data from tensors)

Idexing with pytorch is similar to indexing with numpy

In [50]:
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [51]:
# Indexing on dim = 0
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [52]:
# Indexing on dim = 1
x[0][0]

tensor([1, 2, 3])

In [53]:
# indexing on dim = 2 or last dim
x[0][0][0]

tensor(1)

In [54]:
x[:,:,1]

tensor([[2, 5, 8]])

In [55]:
x[:,:,2]

tensor([[3, 6, 9]])

## Pytorch tensors and Numpy
Numpy is a popular scientific python numerical computing torch.library
and because of this , Pytorch has unctionality to interact with it

* Data in Numpy,want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [56]:
# Numpy array to tensor
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
# warning when converting numpy to pytorch , pytorch reflects numpys default data type of float64
array,tensor


(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [57]:
# Change the value in array
array = array + 1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [58]:
# tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,tensor.dtype,numpy_tensor,numpy_tensor.dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 torch.float32,
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 dtype('float32'))

In [59]:
# What happens if we change the tensor
tensor = tensor + 1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## PYTORCH REPRODUCIBILITY
In short how a neural network learns :

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of data -> again -> again->again...`

To reduce the randomness in neural networks and pytorch comes the concept of a **random seeed**.

Essentially what the random seed does is 'Flavour' the randomness

In [60]:
import torch

# creating two random tensors
tensor_A = torch.rand(3,4)
tensor_B = torch.rand(3,4)

print(tensor_A)
print(tensor_B)
print(tensor_A == tensor_B)

tensor([[0.6718, 0.3729, 0.7431, 0.8458],
        [0.5573, 0.6607, 0.5230, 0.3979],
        [0.3772, 0.0458, 0.9654, 0.7516]])
tensor([[0.1543, 0.8184, 0.3526, 0.7980],
        [0.7465, 0.1555, 0.2571, 0.0319],
        [0.6398, 0.2266, 0.1229, 0.3071]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [61]:
# Lets make some random but reproducible tensor

RANDOM_SEED = 69
torch.manual_seed (RANDOM_SEED)
random_C = torch.rand(3,4)

torch.manual_seed (RANDOM_SEED)
random_D = torch.rand(3,4)

print(random_C)
print(random_D)
print(random_C == random_D)

tensor([[0.8398, 0.8042, 0.1213, 0.5309],
        [0.6646, 0.4077, 0.0888, 0.2429],
        [0.7053, 0.6216, 0.9188, 0.0185]])
tensor([[0.8398, 0.8042, 0.1213, 0.5309],
        [0.6646, 0.4077, 0.0888, 0.2429],
        [0.7053, 0.6216, 0.9188, 0.0185]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [62]:
import torch
torch.cuda.is_available()

True

In [74]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [64]:
torch.cuda.device_count()

1

In [65]:
tensor = torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [66]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4 . move tensor back to cpu

In [67]:
# tensor_on_gpu.numpy()
# ---------------------------------------------------------------------------
# TypeError                                 Traceback (most recent call last)
# /tmp/ipython-input-735472098.py in <cell line: 0>()
# ----> 1 tensor_on_gpu.numpy()

# TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

# will give you this error because the numpy lib only supports on cpu not on gpu only tensors are supported in gpu.

In [69]:
# TO CONVERT FROM GPU TO CPU WE HAVE TO CALL ONE FUNCTION OF .CPU BEFORE
# CONVERTING TO NUMPY
nptensor = tensor_on_gpu.cpu().numpy()
nptensor

array([1, 2, 3])

In [76]:
new_tensor = torch.tensor([1,2,3,4]);
new_tensor.device
new_tensor = new_tensor.to(device)
new_tensor.device

device(type='cuda', index=0)